package http_test

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/Alexandryn/alexandryn/internal/observability"
	"github.com/Alexandryn/alexandryn/internal/testutil"
	transporthttp "github.com/Alexandryn/alexandryn/internal/transport/http"
)

// --- FR-1: composition order — recovery, limits, logging, [auth,
// reserved], routing, each layer's own marker firing in that fixed
// sequence. ---

func TestChain_ComposesInFixedOrder(t *testing.T) {
	var order []string

	marker := func(name string) transporthttp.Middleware {
		return func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				order = append(order, name)
				next.ServeHTTP(w, r)
			})
		}
	}

	routing := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		order = append(order, "routing")
	})

	handler := transporthttp.Chain(routing, marker("recovery"), marker("limits"), marker("logging"))

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	handler.ServeHTTP(httptest.NewRecorder(), req)

	want := []string{"recovery", "limits", "logging", "routing"}
	if len(order) != len(want) {
		t.Fatalf("order = %v, want %v", order, want)
	}
	for i, name := range want {
		if order[i] != name {
			t.Fatalf("order = %v, want %v", order, want)
		}
	}
}

// --- FR-3: panic recovery ---

func TestRecovery_CatchesAPanicAndReturnsInternal(t *testing.T) {
	spy := testutil.NewSpyHandler()
	logger := slog.New(spy)
	ids := testutil.NewFakeIDGenerator("fallback-id-1")

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic("something went wrong")
	})

	handler := transporthttp.Recovery(logger, ids.NewID)(panicking)

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want 500", rec.Code)
	}
	if ct := rec.Header().Get("Content-Type"); ct != "application/json" {
		t.Fatalf("Content-Type = %q, want application/json", ct)
	}

	var body struct {
		Code          string `json:"code"`
		Message       string `json:"message"`
		CorrelationID string `json:"correlationId"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body isn't valid JSON: %v\n%s", err, rec.Body.String())
	}
	if body.Code != "Internal" {
		t.Fatalf("code = %q, want Internal", body.Code)
	}
	if body.CorrelationID == "" {
		t.Fatal("correlationId is empty")
	}
	if strings.Contains(body.Message, "something went wrong") {
		t.Fatalf("panic message leaked into the client-facing body: %q", body.Message)
	}
}

func TestRecovery_GeneratesAFallbackCorrelationIDWhenNoneIsSet(t *testing.T) {
	// A panic before the logging middleware ever ran means the request
	// context carries no correlation ID yet — recovery must generate one
	// itself so the response is never missing one
	// (backend-errors-and-logging.md FR-10).
	logger := slog.New(testutil.NewSpyHandler())
	ids := testutil.NewFakeIDGenerator("recovery-fallback-id")

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic("boom")
	})
	handler := transporthttp.Recovery(logger, ids.NewID)(panicking)

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	var body struct {
		CorrelationID string `json:"correlationId"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body isn't valid JSON: %v", err)
	}
	if body.CorrelationID != "recovery-fallback-id" {
		t.Fatalf("correlationId = %q, want the fallback generated by recovery itself", body.CorrelationID)
	}
}

func TestRecovery_UsesTheExistingCorrelationIDWhenOneIsAlreadySet(t *testing.T) {
	logger := slog.New(testutil.NewSpyHandler())
	ids := testutil.NewFakeIDGenerator("should-not-be-used")

	panicking := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		panic("boom")
	})
	// Simulate logging having already run and attached an ID.
	withID := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r = r.WithContext(transporthttp.WithCorrelationID(r.Context(), "logging-assigned-id"))
			next.ServeHTTP(w, r)
		})
	}

	handler := transporthttp.Recovery(logger, ids.NewID)(withID(panicking))

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	var body struct {
		CorrelationID string `json:"correlationId"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body isn't valid JSON: %v", err)
	}
	if body.CorrelationID != "logging-assigned-id" {
		t.Fatalf("correlationId = %q, want the one already attached by logging", body.CorrelationID)
	}
}

func TestRecovery_NoPanicPassesThroughUnaffected(t *testing.T) {
	logger := slog.New(testutil.NewSpyHandler())
	ids := testutil.NewFakeIDGenerator()

	ok := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusTeapot)
	})
	handler := transporthttp.Recovery(logger, ids.NewID)(ok)

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	if rec.Code != http.StatusTeapot {
		t.Fatalf("status = %d, want 418 (recovery must not interfere when nothing panics)", rec.Code)
	}
}

// backend-errors-and-logging.md FR-10's non-error-panic-value case: a
// nil-valued panic must still be recovered like any other, never
// producing a second panic from the recovery path's own attempt to
// format the value. Go 1.21+ converts panic(nil) to a non-nil
// runtime.PanicNilError specifically so recover() can't mistake it for
// "nothing panicked" — this test proves Recovery handles that value
// correctly rather than relying on the language guarantee alone.
func TestRecovery_PanicWithNilValue_StillRecoversWithoutASecondPanic(t *testing.T) {
	logger := slog.New(testutil.NewSpyHandler())
	ids := testutil.NewFakeIDGenerator("nil-panic-id")

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic(nil)
	})
	handler := transporthttp.Recovery(logger, ids.NewID)(panicking)

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want 500", rec.Code)
	}

	var body struct {
		Code          string `json:"code"`
		CorrelationID string `json:"correlationId"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body isn't valid JSON: %v", err)
	}
	if body.Code != "Internal" {
		t.Fatalf("code = %q, want Internal", body.Code)
	}
	if body.CorrelationID == "" {
		t.Fatal("correlationId is empty")
	}
}

// --- FR-4: logging middleware skeleton ---

func TestLogging_EmitsDebugStartAndInfoCompletionWithTheSameCorrelationID(t *testing.T) {
	spy := testutil.NewSpyHandler()
	logger := slog.New(spy)
	ids := testutil.NewFakeIDGenerator("req-1")

	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusCreated)
	})
	handler := transporthttp.Logging(logger, ids.NewID)(next)

	req := httptest.NewRequest(http.MethodPost, "/widgets", nil)
	handler.ServeHTTP(httptest.NewRecorder(), req)

	records := spy.Records()
	if len(records) != 2 {
		t.Fatalf("got %d log records, want 2 (start + completion)", len(records))
	}

	start, completion := records[0], records[1]
	if start.Level != slog.LevelDebug {
		t.Fatalf("start record level = %v, want debug", start.Level)
	}
	if completion.Level != slog.LevelInfo {
		t.Fatalf("completion record level = %v, want info", completion.Level)
	}

	attrs := func(r slog.Record) map[string]string {
		m := map[string]string{}
		r.Attrs(func(a slog.Attr) bool {
			m[a.Key] = a.Value.String()
			return true
		})
		return m
	}

	startAttrs, completionAttrs := attrs(start), attrs(completion)

	if startAttrs["correlationId"] != "req-1" || completionAttrs["correlationId"] != "req-1" {
		t.Fatalf("correlation IDs = %q / %q, want both req-1", startAttrs["correlationId"], completionAttrs["correlationId"])
	}
	if completionAttrs["method"] != "POST" {
		t.Fatalf("completion method = %q, want POST", completionAttrs["method"])
	}
	if completionAttrs["path"] != "/widgets" {
		t.Fatalf("completion path = %q, want /widgets", completionAttrs["path"])
	}
	if completionAttrs["status"] != "201" {
		t.Fatalf("completion status = %q, want 201", completionAttrs["status"])
	}
	if completionAttrs["duration"] == "" {
		t.Fatal("completion duration attr is empty")
	}
}

func TestLogging_AttachesTheCorrelationIDToTheRequestContext(t *testing.T) {
	logger := slog.New(testutil.NewSpyHandler())
	ids := testutil.NewFakeIDGenerator("ctx-id")

	var seen string
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen = transporthttp.CorrelationIDFromContext(r.Context())
	})
	handler := transporthttp.Logging(logger, ids.NewID)(next)

	handler.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/", nil))

	if seen != "ctx-id" {
		t.Fatalf("correlation ID seen by the handler = %q, want ctx-id", seen)
	}
}

// FR-7: the ID MUST be randomly generated, "never derived from anything
// request-supplied" — a client-supplied X-Correlation-Id header must
// never be trusted as the log-tying value, well-formed or not, since
// that would let a malicious client inject an ID chosen to collide with
// or spoof another request's logs.
func TestLogging_IgnoresClientSuppliedCorrelationIDHeader(t *testing.T) {
	cases := []struct {
		name   string
		header string
	}{
		{"well-formed spoofed value", "client-supplied-spoofed-id"},
		{"malformed value", "\x00not\x01valid\x02"},
		{"empty value", ""},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			logger := slog.New(testutil.NewSpyHandler())
			ids := testutil.NewFakeIDGenerator("server-generated-id")

			var seen string
			next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				seen = transporthttp.CorrelationIDFromContext(r.Context())
			})
			handler := transporthttp.Logging(logger, ids.NewID)(next)

			req := httptest.NewRequest(http.MethodGet, "/", nil)
			req.Header.Set("X-Correlation-Id", tc.header)
			handler.ServeHTTP(httptest.NewRecorder(), req)

			if seen != "server-generated-id" {
				t.Fatalf("correlation ID seen by handler = %q, want the server-generated one regardless of the client-supplied header", seen)
			}
		})
	}
}

// Regression guard: Recovery wraps Logging, exactly as the real chain
// composes them (FR-1). A panic after Logging has already assigned a
// correlation ID must surface that same ID in the response, not a
// fallback — proving the two middlewares actually share state across
// the real call stack, not just when tested against a hand-simulated
// context value.
func TestRecovery_WrappingLogging_UsesLoggingsRealCorrelationID(t *testing.T) {
	logger := slog.New(testutil.NewSpyHandler())
	recoveryIDs := testutil.NewFakeIDGenerator("should-not-be-used")
	loggingIDs := testutil.NewFakeIDGenerator("logging-real-id")

	panicking := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		panic("boom")
	})

	handler := transporthttp.Chain(panicking,
		transporthttp.Recovery(logger, recoveryIDs.NewID),
		transporthttp.Logging(logger, loggingIDs.NewID),
	)

	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	var body struct {
		CorrelationID string `json:"correlationId"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body isn't valid JSON: %v", err)
	}
	if body.CorrelationID != "logging-real-id" {
		t.Fatalf("correlationId = %q, want logging's own ID, not a fallback", body.CorrelationID)
	}
}

func TestCorrelationIDFromContext_EmptyWhenNoneSet(t *testing.T) {
	if got := transporthttp.CorrelationIDFromContext(context.Background()); got != "" {
		t.Fatalf("CorrelationIDFromContext(bare context) = %q, want empty", got)
	}
}

func TestMetrics_ObservesRouteLatencyAndIgnoresAssets(t *testing.T) {
	reg := observability.NewRegistry()
	endpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	handler := transporthttp.Metrics(reg, nil)(endpoint)

	// API request
	req1 := httptest.NewRequest(http.MethodGet, "/api/v1/library", nil)
	req1.Pattern = "GET /api/v1/library"
	handler.ServeHTTP(httptest.NewRecorder(), req1)

	// Static asset request
	req2 := httptest.NewRequest(http.MethodGet, "/assets/index.js", nil)
	handler.ServeHTTP(httptest.NewRecorder(), req2)

	snap, err := reg.Snapshot(context.Background())
	if err != nil {
		t.Fatalf("Snapshot: %v", err)
	}

	if hist, ok := snap.Latencies["GET /api/v1/library"]; !ok || hist.Count != 1 {
		t.Errorf("Latencies[GET /api/v1/library] = %+v, want count 1", hist)
	}
	if _, ok := snap.Latencies["/assets/index.js"]; ok {
		t.Errorf("expected /assets/index.js to be ignored in metrics")
	}
}

// audit 0016 #293: with a mux, the route label is the registered pattern
// regardless of whether r.Pattern was populated, so a path with a
// per-request id does not spawn a fresh histogram, and an unmatched path
// is bucketed rather than labelled with its raw URL.
func TestMetrics_LabelsByRegisteredPatternNotRawPath(t *testing.T) {
	reg := observability.NewRegistry()
	mux := http.NewServeMux()
	mux.HandleFunc("GET /api/v1/works/{id}", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	// Metrics wraps a middleware that strips r.Pattern, standing in for
	// the real chain's WithContext layers between Metrics and the mux.
	stripPattern := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r2 := r.Clone(r.Context())
			r2.Pattern = ""
			next.ServeHTTP(w, r2)
		})
	}
	handler := transporthttp.Metrics(reg, mux)(stripPattern(mux))

	for _, id := range []string{"w-1", "w-2", "w-3"} {
		req := httptest.NewRequest(http.MethodGet, "/api/v1/works/"+id, nil)
		handler.ServeHTTP(httptest.NewRecorder(), req)
	}
	unmatched := httptest.NewRequest(http.MethodGet, "/api/v1/does-not-exist/xyz", nil)
	handler.ServeHTTP(httptest.NewRecorder(), unmatched)

	snap, err := reg.Snapshot(context.Background())
	if err != nil {
		t.Fatalf("Snapshot: %v", err)
	}
	if hist, ok := snap.Latencies["GET /api/v1/works/{id}"]; !ok || hist.Count != 3 {
		t.Fatalf("Latencies[GET /api/v1/works/{id}] = %+v, want count 3", hist)
	}
	if _, ok := snap.Latencies["/api/v1/works/w-1"]; ok {
		t.Fatal("a raw per-id path was recorded as its own metric label")
	}
	if _, ok := snap.Latencies["unmatched"]; !ok {
		t.Fatal("an unmatched path was not bucketed under \"unmatched\"")
	}
	if len(snap.Latencies) != 2 {
		t.Fatalf("recorded %d distinct route labels, want 2 (bounded)", len(snap.Latencies))
	}
}

