-- Phase 02's 11 domain aggregates (backend-persistence.md FR-2) plus the
-- outbox table (ADR 0021, a 12th persisted thing, no domain type).
--
-- TEXT primary keys throughout, matching the domain's own string-based
-- ID types (WorkID, EditionID, ...) — no UUID column type needed, since
-- the ID *value* is already a UUID string generated by internal/idgen.
-- Column names are snake_case (this project's existing DB-column
-- convention, distinct from the wire's camelCase).
--
-- Value types embedded within an aggregate (Subject, Language,
-- ExternalReference, FileReference) and the many-to-many/one-to-many
-- collections a single aggregate owns (a Work's authors/subjects/
-- external references/contains, a Collection's members) get their own
-- child table, one row per element, rather than a JSON column — normal
-- relational normalization, not a departure from "one repository per
-- aggregate" (backend-persistence.md FR-2's own Domain model section:
-- that rule is about repository *types*, not table count).
--
-- The outbox table (T24-D4, tasks/plan-t24-repositories.md) is built
-- now because FR-2's own list requires it to exist, but nothing writes
-- to it yet — no real caller (a feature phase composing a domain
-- service's returned event with persistence) exists to exercise a
-- writer honestly. Its shape may need revision once one does.

-- +goose Up

CREATE TABLE works (
    id                 TEXT PRIMARY KEY,
    title              TEXT NOT NULL,
    subtitle           TEXT NOT NULL DEFAULT '',
    original_language  TEXT,
    merged_into        TEXT REFERENCES works(id)
);

-- domain-bibliographic.md FR-1: Work MAY reference zero or more Authors.
CREATE TABLE work_authors (
    work_id    TEXT NOT NULL REFERENCES works(id),
    author_id  TEXT NOT NULL,
    PRIMARY KEY (work_id, author_id)
);

-- Subject is a value type (no identity of its own) — the subject text
-- itself, plus which Work it's attached to, is the whole row.
CREATE TABLE work_subjects (
    work_id  TEXT NOT NULL REFERENCES works(id),
    subject  TEXT NOT NULL,
    PRIMARY KEY (work_id, subject)
);

-- ExternalReference (Source, ID) is a value type, reused identically for
-- Work, Edition, and Author — three child tables, same two-column shape.
CREATE TABLE work_external_references (
    work_id      TEXT NOT NULL REFERENCES works(id),
    source       TEXT NOT NULL,
    external_id  TEXT NOT NULL,
    PRIMARY KEY (work_id, source, external_id)
);

-- domain-bibliographic.md FR-9: the omnibus containment graph.
-- container_work_id contains containee_work_id.
CREATE TABLE work_contains (
    container_work_id  TEXT NOT NULL REFERENCES works(id),
    containee_work_id  TEXT NOT NULL REFERENCES works(id),
    PRIMARY KEY (container_work_id, containee_work_id)
);

CREATE TABLE authors (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    merged_into  TEXT REFERENCES authors(id)
);

CREATE TABLE author_external_references (
    author_id    TEXT NOT NULL REFERENCES authors(id),
    source       TEXT NOT NULL,
    external_id  TEXT NOT NULL,
    PRIMARY KEY (author_id, source, external_id)
);

-- domain-bibliographic.md FR-8: an Edition cannot exist without a parent
-- Work — work_id NOT NULL with no default is this table's own version of
-- that type-level guarantee.
CREATE TABLE editions (
    id                 TEXT PRIMARY KEY,
    work_id            TEXT NOT NULL REFERENCES works(id),
    language           TEXT NOT NULL,
    isbn               TEXT,
    publisher          TEXT NOT NULL DEFAULT '',
    publication_year   INTEGER
);

CREATE TABLE edition_external_references (
    edition_id   TEXT NOT NULL REFERENCES editions(id),
    source       TEXT NOT NULL,
    external_id  TEXT NOT NULL,
    PRIMARY KEY (edition_id, source, external_id)
);

-- domain-library.md FR-7: at most one LibraryEntry per Edition — the
-- UNIQUE constraint is the real enforcement (R6's own concurrency proof
-- target), not just an index.
CREATE TABLE library_entries (
    id          TEXT PRIMARY KEY,
    edition_id  TEXT NOT NULL UNIQUE REFERENCES editions(id),
    added_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE collections (
    id    TEXT PRIMARY KEY,
    name  TEXT NOT NULL
);

-- domain-library.md FR-9: each membership carries its own added-at
-- timestamp, independent of any LibraryEntry's.
CREATE TABLE collection_members (
    collection_id  TEXT NOT NULL REFERENCES collections(id),
    work_id        TEXT NOT NULL REFERENCES works(id),
    added_at       TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (collection_id, work_id)
);

CREATE TABLE sources (
    id            TEXT PRIMARY KEY,
    label         TEXT NOT NULL,
    can_list      BOOLEAN NOT NULL,
    can_search    BOOLEAN NOT NULL,
    can_download  BOOLEAN NOT NULL,
    kind          TEXT NOT NULL DEFAULT ''
);

-- domain-source.md FR-2: uniquely identified by (Source, Edition,
-- Format) — the UNIQUE constraint below is R7's own real-constraint
-- proof target, matching SourceOffering.UniquenessKey() at the Go level.
-- file_reference_* columns are FileReference's three fields flattened
-- (it's a value type embedded in this aggregate, not its own table,
-- since it has no independent existence or identity beyond one
-- SourceOffering).
CREATE TABLE source_offerings (
    id                          TEXT PRIMARY KEY,
    source_id                   TEXT NOT NULL REFERENCES sources(id),
    edition_id                  TEXT NOT NULL REFERENCES editions(id),
    file_reference_id           TEXT NOT NULL,
    file_reference_format       TEXT NOT NULL,
    file_reference_size_bytes   BIGINT,
    observed_at                 TIMESTAMPTZ NOT NULL,
    UNIQUE (source_id, edition_id, file_reference_format)
);

-- domain-reading.md FR-1: at most one ReadingProgress per Work — the
-- UNIQUE constraint on work_id is R8's own real-constraint proof target.
-- precise_position_* columns are PrecisePosition's two fields flattened,
-- both nullable together (FR-2: a PrecisePosition is optional).
CREATE TABLE reading_progress (
    id                            TEXT PRIMARY KEY,
    work_id                       TEXT NOT NULL UNIQUE REFERENCES works(id),
    percentage                    DOUBLE PRECISION NOT NULL,
    precise_position_edition_id   TEXT REFERENCES editions(id),
    precise_position_value        TEXT,
    device_id                     TEXT NOT NULL,
    observed_at                   TIMESTAMPTZ NOT NULL
);

CREATE TABLE bookmarks (
    id          TEXT PRIMARY KEY,
    edition_id  TEXT NOT NULL REFERENCES editions(id),
    position    TEXT NOT NULL,
    label       TEXT NOT NULL DEFAULT ''
);

CREATE TABLE highlights (
    id              TEXT PRIMARY KEY,
    edition_id      TEXT NOT NULL REFERENCES editions(id),
    start_position  TEXT NOT NULL,
    end_position    TEXT NOT NULL,
    note            TEXT NOT NULL DEFAULT '',
    category        TEXT NOT NULL DEFAULT ''
);

-- domain-reading.md FR-5: one row per DeviceID — device_id is the
-- natural primary key, since ReadingPreferences has no ID field of its
-- own in the domain model. settings is FR-5's opaque, phase-11-defined
-- bag, stored as JSONB rather than a fixed column set for exactly that
-- reason.
CREATE TABLE reading_preferences (
    device_id  TEXT PRIMARY KEY,
    settings   JSONB NOT NULL DEFAULT '{}'
);

-- ADR 0021: every event domain-events.md FR-5 requires, written in the
-- same transaction as the mutation it describes. Schema only — no
-- repository writes to this table yet (T24-D4).
CREATE TABLE outbox (
    id            TEXT PRIMARY KEY,
    event_type    TEXT NOT NULL,
    aggregate_id  TEXT NOT NULL,
    payload       JSONB,
    occurred_at   TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- +goose Down

DROP TABLE outbox;
DROP TABLE reading_preferences;
DROP TABLE highlights;
DROP TABLE bookmarks;
DROP TABLE reading_progress;
DROP TABLE source_offerings;
DROP TABLE sources;
DROP TABLE collection_members;
DROP TABLE collections;
DROP TABLE library_entries;
DROP TABLE edition_external_references;
DROP TABLE editions;
DROP TABLE author_external_references;
DROP TABLE authors;
DROP TABLE work_contains;
DROP TABLE work_external_references;
DROP TABLE work_subjects;
DROP TABLE work_authors;
DROP TABLE works;
